<?php
/**
 * Drapeau (emoji) à partir d'un nom de pays en français, tel qu'exporté par
 * FM26 dans la colonne "Nation" de l'effectif (voir upload.php, champ `nat`).
 *
 * Emojis codés en dur (et non recomposés via mb_chr à partir du code ISO) :
 * la version calculée dynamiquement s'affichait correctement en local mais
 * pas en prod (probablement un mb_internal_encoding different cote
 * hebergeur), alors que les emojis litteraux (comme les drapeaux du
 * selecteur de langue dans navbar.php/usermenu.php) s'affichent partout.
 *
 * Couvre les nations courantes en jeu. Un pays absent de la table renvoie
 * simplement une chaîne vide (pas de drapeau) plutôt qu'un symbole erroné.
 */

const FMXX_COUNTRY_FLAGS = [
    'Afghanistan' => '🇦🇫',
    'Afrique du Sud' => '🇿🇦',
    'Albanie' => '🇦🇱',
    'Algérie' => '🇩🇿',
    'Allemagne' => '🇩🇪',
    'Andorre' => '🇦🇩',
    'Angleterre' => '🇬🇧',
    'Angola' => '🇦🇴',
    'Arabie saoudite' => '🇸🇦',
    'Argentine' => '🇦🇷',
    'Arménie' => '🇦🇲',
    'Australie' => '🇦🇺',
    'Autriche' => '🇦🇹',
    'Azerbaïdjan' => '🇦🇿',
    'Bahreïn' => '🇧🇭',
    'Belgique' => '🇧🇪',
    'Bénin' => '🇧🇯',
    'Biélorussie' => '🇧🇾',
    'Bolivie' => '🇧🇴',
    'Bosnie-Herzégovine' => '🇧🇦',
    'Botswana' => '🇧🇼',
    'Brésil' => '🇧🇷',
    'Bulgarie' => '🇧🇬',
    'Burkina Faso' => '🇧🇫',
    'Cambodge' => '🇰🇭',
    'Cameroun' => '🇨🇲',
    'Canada' => '🇨🇦',
    'Cap-Vert' => '🇨🇻',
    'Chili' => '🇨🇱',
    'Chine' => '🇨🇳',
    'Chypre' => '🇨🇾',
    'Colombie' => '🇨🇴',
    'Congo' => '🇨🇬',
    'RD Congo' => '🇨🇩',
    'Corée du Nord' => '🇰🇵',
    'Corée du Sud' => '🇰🇷',
    'Costa Rica' => '🇨🇷',
    'Côte d\'Ivoire' => '🇨🇮',
    'Croatie' => '🇭🇷',
    'Cuba' => '🇨🇺',
    'Danemark' => '🇩🇰',
    'Égypte' => '🇪🇬',
    'Émirats arabes unis' => '🇦🇪',
    'Équateur' => '🇪🇨',
    'Écosse' => '🇬🇧',
    'Espagne' => '🇪🇸',
    'Estonie' => '🇪🇪',
    'États-Unis' => '🇺🇸',
    'Éthiopie' => '🇪🇹',
    'Finlande' => '🇫🇮',
    'France' => '🇫🇷',
    'Gabon' => '🇬🇦',
    'Galles' => '🇬🇧',
    'Gambie' => '🇬🇲',
    'Géorgie' => '🇬🇪',
    'Ghana' => '🇬🇭',
    'Grèce' => '🇬🇷',
    'Guatemala' => '🇬🇹',
    'Guinée' => '🇬🇳',
    'Haïti' => '🇭🇹',
    'Honduras' => '🇭🇳',
    'Hongrie' => '🇭🇺',
    'Inde' => '🇮🇳',
    'Indonésie' => '🇮🇩',
    'Irak' => '🇮🇶',
    'Iran' => '🇮🇷',
    'Irlande' => '🇮🇪',
    'Irlande du Nord' => '🇬🇧',
    'Islande' => '🇮🇸',
    'Israël' => '🇮🇱',
    'Italie' => '🇮🇹',
    'Jamaïque' => '🇯🇲',
    'Japon' => '🇯🇵',
    'Jordanie' => '🇯🇴',
    'Kazakhstan' => '🇰🇿',
    'Kenya' => '🇰🇪',
    'Kosovo' => '🇽🇰',
    'Koweït' => '🇰🇼',
    'Lettonie' => '🇱🇻',
    'Liban' => '🇱🇧',
    'Libye' => '🇱🇾',
    'Lituanie' => '🇱🇹',
    'Luxembourg' => '🇱🇺',
    'Macédoine du Nord' => '🇲🇰',
    'Madagascar' => '🇲🇬',
    'Malaisie' => '🇲🇾',
    'Mali' => '🇲🇱',
    'Malte' => '🇲🇹',
    'Maroc' => '🇲🇦',
    'Mexique' => '🇲🇽',
    'Moldavie' => '🇲🇩',
    'Monaco' => '🇲🇨',
    'Mongolie' => '🇲🇳',
    'Monténégro' => '🇲🇪',
    'Mozambique' => '🇲🇿',
    'Namibie' => '🇳🇦',
    'Nicaragua' => '🇳🇮',
    'Niger' => '🇳🇪',
    'Nigeria' => '🇳🇬',
    'Norvège' => '🇳🇴',
    'Nouvelle-Zélande' => '🇳🇿',
    'Oman' => '🇴🇲',
    'Ouganda' => '🇺🇬',
    'Ouzbékistan' => '🇺🇿',
    'Pakistan' => '🇵🇰',
    'Panama' => '🇵🇦',
    'Paraguay' => '🇵🇾',
    'Pays-Bas' => '🇳🇱',
    'Pérou' => '🇵🇪',
    'Philippines' => '🇵🇭',
    'Pologne' => '🇵🇱',
    'Portugal' => '🇵🇹',
    'Qatar' => '🇶🇦',
    'République dominicaine' => '🇩🇴',
    'République tchèque' => '🇨🇿',
    'Roumanie' => '🇷🇴',
    'Russie' => '🇷🇺',
    'Rwanda' => '🇷🇼',
    'Salvador' => '🇸🇻',
    'Sénégal' => '🇸🇳',
    'Serbie' => '🇷🇸',
    'Singapour' => '🇸🇬',
    'Slovaquie' => '🇸🇰',
    'Slovénie' => '🇸🇮',
    'Soudan' => '🇸🇩',
    'Sri Lanka' => '🇱🇰',
    'Suède' => '🇸🇪',
    'Suisse' => '🇨🇭',
    'Syrie' => '🇸🇾',
    'Tanzanie' => '🇹🇿',
    'Tchad' => '🇹🇩',
    'Thaïlande' => '🇹🇭',
    'Togo' => '🇹🇬',
    'Trinité-et-Tobago' => '🇹🇹',
    'Tunisie' => '🇹🇳',
    'Turquie' => '🇹🇷',
    'Ukraine' => '🇺🇦',
    'Uruguay' => '🇺🇾',
    'Venezuela' => '🇻🇪',
    'Viêt Nam' => '🇻🇳',
    'Zambie' => '🇿🇲',
    'Zimbabwe' => '🇿🇼',
];

if (!function_exists('fmxx_flag_emoji')) {
    function fmxx_flag_emoji(?string $countryNameFr): string {
        if (!$countryNameFr) return '';
        return FMXX_COUNTRY_FLAGS[trim($countryNameFr)] ?? '';
    }
}
